#!/bin/bash
source_dir=$(pwd)
dest_dir=$(dirname "$source_dir")

for file in "$source_dir"/*.html; do
    if [ -e "$dest_dir/$(basename "$file")" ]; then
        source_time=$(date -r "$file" +%s)
        dest_time=$(date -r "$dest_dir/$(basename "$file")" +%s)
        if [ "$source_time" -gt "$dest_time" ]; then
            cp "$file" "$dest_dir"
        fi
    else
        cp "$file" "$dest_dir"
    fi
done

